# Default docs params

# Doc versions params
# Create a separate [[versions]] set for every version / doc set branch
# Use the ghbranchname param for specifying the GitHub branchname ->
# Example:
#   [thisisalink](https://github.com/.../tree/{{< params "ghbranchname" >}}/...)
#
# [[versions]] - Defines a single "version" of the docs
#   version - Intuitive version label (ie. visible in menus)
#   ghbranchname - Name of branch of the doc version in GitHub
#                  (https://github.com/cert-manager/docs/branches)
#   url - Fully qualified website URL to the doc version
#         (ie. https://cert-manager.io/[dirpath])
#   dirpath - The content folder name of the doc version
#           - Latest release is always set to "docs"
#           - Past/archived releases change to "v#.#-docs",
#             where # is the MAJOR and MINOR semantic version values

# Latest version
################
# Set to "docs" path

[[versions]]
  version = "v1.2"
  # 'master' is used to store the 'current' version documentation.
  # Once the 'next' release becomes 'current', we branch master to
  # release-X.Y and merge 'release-next' into 'master'.
  ghbranchname = "master"
  url = "/docs/"
  dirpath = "docs"

# 'Next' version
################
[[versions]]
  version = "v1.3"
  ghbranchname = "release-next"
  url = "/next-docs/"
  dirpath = "next-docs"

# Archived versions
###################
# Use format `v0.#-docs` for past version's dirpath


[[versions]]
  version = "v1.0"
  ghbranchname = "release-1.0"
  url = "/v1.0-docs/"
  dirpath = "v1.0-docs"

[[versions]]
  version = "v0.16"
  ghbranchname = "release-0.16"
  url = "/v0.16-docs/"
  dirpath = "v0.16-docs"

[[versions]]
  version = "v0.15"
  ghbranchname = "release-0.15"
  url = "/v0.15-docs/"
  dirpath = "v0.15-docs"

[[versions]]
  version = "v0.14"
  ghbranchname = "release-0.14"
  url = "/v0.14-docs/"
  dirpath = "v0.14-docs"

[[versions]]
  version = "v0.13"
  ghbranchname = "release-0.13"
  url = "/v0.13-docs/"
  dirpath = "v0.13-docs"

[[versions]]
  version = "v0.12"
  ghbranchname = "release-0.12"
  url = "/v0.12-docs/"
  dirpath = "v0.12-docs"

[[versions]]
  version = "v0.11"
  ghbranchname = "release-0.11"
  url = "https://docs.cert-manager.io/en/release-0.11"
  dirpath = "external-link"
